config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  get 'search', to: 'search#search'
  get 'dashboard', to: 'dashboard#index', as: :dashboard
  get 'summon_modal', to: 'search#summon_modal', as: :summon_modal
  post 'create_new_item', to:'search#create_item', as: :create_item
  post 'new_meal_card', to: 'dashboard#new_card'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord

  def self.search_item_by_name(item_name)
    @name = FoodItem.where(name: "#{item_name}").first
    @name
  end

  def self.create_entry(name, protein, fat, carbs)
    # if food item doesnt exist, create it
    if FoodItem.where(name: "#{name}").first.nil?
      FoodItem.create(name: name,
                      protein: protein,
                      fat: fat,
                      carbs: carbs)
    else
      # return message that the item already exists
      puts "Item already exists meow meow"
      raise "ItemExistsError"
    end
  end

  def self.update_name(name, macro, value)
    item = FoodItem.where(name: name).first
    case macro.downcase
    when 'protein'
      item.protein(value)
    when 'fat'
      item.fat(value)
    when 'carbs'
      item.carbs(value)
    end
  end

  def self.total_entries
    return FoodItem.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def index
    render('dashboard/index')
  end


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

  def new_card
    @carbs = params[:carbs]
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/food_item_controller.rb
class FoodItemController < ApplicationController

  def add_item
    FoodItem.add_item(params[:name], params[:protein], params[:fat], params[:carbs])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    @macro = FoodItem.search_item_by_name(params[:search])
    @macro
    # render 'dashboard/index'
    respond_to do |format|
      format.js 
    end
  end

  def summon_modal
    respond_to do |format|
      format.html
    end
  end

  def create_item
    food_name = params["create_item"]["name"]
    protein = params["create_item"]["protein"]
    fat = params["create_item"]["fat"]
    carbs = params["create_item"]["carbs"]
    # TODO: Add validation for food name
    before_count = FoodItem.total_entries
    new_food_item = FoodItem.create_entry(food_name, protein, fat, carbs)
    after_count = FoodItem.total_entries
    if after_count > before_count
      flash[:notice] = "Food item successfully created"
    else
      flash[:error] = "Could not save food item"
    end
    redirect_to '/'
  end

end

app/helpers/add_food_item_helper.rb
module AddFoodItemHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/application_partials/_add_food_to_card.html.erb
<%= javascript_include_tag('add_to_list.js') %>

<div class="modal-dialog" role="document">
  <div class="modal-content" id="create-food-item-modal">
    <div class="modal-header">
      <h5 class="modal-title">Add food to <strong>No Carb meal 1</strong></h5>
      <button type="button" class="close close-modal" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="form-row">
        <div class="col">
          <p class="modal-item-text">oz or g:</p>
        </div>
        <div class="col">
          <input class="form-control"  id="meal-card-amount" type="text" name="" placeholder="amount example: 150" value="">
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" id="add-card-btn" data-dismiss="modal" onclick="addFoodItemsToList()">+ Add to card</button>
      <button type="button" class="btn btn-secondary close-modal" data-dismiss="modal">Close</button>
    </div>
  </div>
</div>

app/views/application_partials/_create_item.html.erb
  <div class="modal-dialog" role="document">
    <%= form_for :create_item, :url => create_item_url, :method => 'post' do |f| %>
    <div class="modal-content" id="create-food-item-modal">
      <div class="modal-header">
        <h5 class="modal-title">Create Food item +</h5>
        <button type="button" class="close close-modal" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-row">
          <div class="col">
            <p class="modal-item-text">Food name:</p>
            <p class="modal-item-text">Protein per 1g:</p>
            <p class="modal-item-text">Fat per 1g:</p>
            <p class="modal-item-text">Carbs per 1g:</p>
          </div>
          <div class="col">
            <%= f.text_field :name, class: 'form-control', value: params[:search] %>
            <%= f.text_field :protein, class: 'form-control', placeholder: "Protein" %>
            <%= f.text_field :fat, class: 'form-control', placeholder: "Fat" %>
            <%= f.text_field :carbs, class: 'form-control', placeholder: "Carbs" %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit "Save Changes", class: "btn btn-secondary close-modal" %>
        <button type="button" class="btn btn-secondary close-modal" data-dismiss="modal">Close</button>
      </div>
    </div>
    <% end %>
  </div>

app/views/application_partials/_daily_meal_card.html.erb
<div class="card daily-card" id="meow">
  <ul class="list-group list-group-flush meal-list">
    <li class="list-group-item"><h1 class="display-4 meal-card-header">meal 1</h1></li>
    <div class="meal-card-header">
      <form action="index.html" method="get">
        <button type="button" class="btn btn-success add-search-btn" data-toggle="modal" data-target="#addFoodToCardModal" id="add-search-button" onclick="grabFoodValues()">
          + Add from search
        </button>
      </form>
    </div>
    <li class="list-group-item">
      <ul class="list-inline">
        <li class="list-inline-item card-protein">Protein 80g</li>
        <li class="list-inline-item card-fat">Fat 200g</li>
        <li class="list-inline-item card-carbs">Carbs 325g</li>
      </ul>
    </li>
    <li class="list-group-item">
      <ul class="list-inline meal-card-list">
        <ul class="list-inline">
          <!-- Food List items are appended here  -->
        </ul>
      </ul>
    </li>
    <div class="modal fade" id="addFoodToCardModal" tabindex="-1" role="dialog" aria-labelledby="createFoodModalLabel" aria-hidden="true">
      <%= render 'application_partials/add_food_to_card' %>
    </div>
  </ul>
</div>

app/views/application_partials/_daily_summary_card.html.erb
<div class="card" style="width: 16rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><h2>Average Daily Macro Summary</h2></li>
    <li class="list-group-item card-protein">Protein: 0g</li>
    <li class="list-group-item card-fat">Fat: 0g</li>
    <li class="list-group-item card-carbs">Carbs: 0g</li>
  </ul>
</div>

app/views/application_partials/_meow.html.erb
<h1>MEOW MEOW CHIGGY</h1>

app/views/application_partials/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">MealPrepr</a>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">Meow</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Meow2</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Meow3</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Meow4</a>
      </li>
    </ul>
  </div>
</div>

app/views/application_partials/_search.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Search for food item</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <form action="<%= search_path %>" method="get">
          <%= text_field_tag(:search, params[:search], placeholder: "Search food item", autofocus: true, class: "form-control mr-sm-2" ) %>
          <%= button_tag(type: :submit, class: 'btn btn-outline-success my-2 my-sm-0') do %>
          Search
          <% end %>
        </form>
      </td>
      <th scope="col">Amount</th>
      <th scope="col">Protein</th>
      <th scope="col">Fat</th>
      <th scope="col">Carbs</th>
      <th></th>
    </tr>
    <tr>
      <%= render "application_partials/search_results" %>
    </tr>
  </tbody>
</table>

app/views/application_partials/_search_form.html.erb
<tr>
  <td>
    <nav class="navbar navbar-light bg-light">
      <form class="form-inline" action="<%= search_path %>" method="get" remote = true>
        <%= text_field_tag(:search, params[:search], placeholder: "Search food item", autofocus: true, class: "form-control mr-sm-2", id: 'search-food-item', ) %>
        <%= button_tag(type: :submit, class: 'btn btn-outline-success my-2 my-sm-0') do %>
        Search
        <% end %>
      </form>
    </nav>
  </td>
  <th scope="col">Amount</th>
  <th scope="col" class="card-protein">Protein</th>
  <th scope="col" class="card-fat">Fat</th>
  <th scope="col" class="card-carbs">Carbs</th>
</tr>

app/views/application_partials/_search_results.html.erb
<% if @macro.nil? %>
  <% if params[:search].blank? %>
    <td>
    </td>
  <% else %>
    <td>
      <form>
        Sorry, I couldnt find  "<%= params[:search] %>"
        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#createFoodModal" id="create-food-modal">
          + create item?
        </button>
      </form>
    </td>
  <% end %>
  <td>0g</td>
  <td>0g</td>
  <td>0g</td>
  <td>0g</td>
<% else %>
  <td id="macro-name"><%= @macro.name %></td>
  <td>1g</td>
  <td class="card-protein"><%= @macro.protein %></td>
  <td class="card-fat"><%= @macro.fat %></td>
  <td class="card-carbs"><%= @macro.carbs %></td>
<% end %>

<div class="modal fade" id="createFoodModal" tabindex="-1" role="dialog" aria-labelledby="createFoodModalLabel" aria-hidden="true">
  <%= render 'application_partials/create_item' %>
</div>

app/views/dashboard/index.html.erb
<%= render "application_partials/navbar" %>
<div class="container">
  <div class="row header-row">
    <div class="col-10">
      <!--  Rendering view for search -->
      <div class="table-responsive-sm">
        <% if flash[:notice] %>
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <strong>Meow!</strong> <%= flash[:notice] %>
          </div>
        <% end %>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Search for food item</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <nav class="navbar navbar-light bg-light">
                  <%= form_tag '/search', class: "form-inline", method: :get, remote: true do %>
                    <%= text_field_tag(:search, params[:search], placeholder: "Search food item", autofocus: true, class: "form-control mr-sm-2", id: 'search-food-item', ) %>
                    <%= button_tag(type: :submit, class: 'btn btn-outline-success my-2 my-sm-0') do %>
                    Search
                    <% end %>
                  <% end %>
                </nav>
              </td>
              <th scope="col">Amount</th>
              <th scope="col" class="card-protein">Protein</th>
              <th scope="col" class="card-fat">Fat</th>
              <th scope="col" class="card-carbs">Carbs</th>
            </tr>
            <tr id="searchForm">

            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <h1 style="text-align: center">Weekly Meal Cards</h1>
  <div class="row justify-content-md-center" style="padding-top: 50px;">
    <!-- No Carb column starts here -->
    <div class="col h-100 d-inline-block odd-col daily-lane rounded" id="noCarbCol">
      <div class="meal-card-header">
        <h2 class="display-3" style="text-align: center">No Carb</h2>
        <%= form_tag '/new_meal_card', method: :post, remote: true do %>
          <%= hidden_field_tag "carbs", "no-carbs" %>
          <%= submit_tag "+ New Meal", class: "btn btn-success new-meal-button" %>
        <% end %>
      </div>
      <%= render 'application_partials/daily_meal_card' %>
      <div class="nocarb">

      </div>
    </div>
    <!-- High Carb column starts here  -->
    <div class="col daily-lane rounded" style="background-color: #c5e0d2" id="highCarbCol">
      <div class="meal-card-header">
        <h2 class="display-3" style="text-align: center">High Carb</h2>
        <%= form_tag '/new_meal_card', method: :post, remote: true do %>
          <%= hidden_field_tag "carbs", "high-carbs" %>
          <%= submit_tag "+ New Meal", class: "btn btn-success new-meal-button" %>
        <% end %>
      </div>
      <%= render 'application_partials/daily_meal_card' %>
      <div class="highcarb">

      </div>
    </div>
    <!-- Low Carb column starts here -->
    <div class="col h-100 d-inline-block odd-col daily-lane rounded" id="lowCarbCol">
      <div class="meal-card-header">
        <h2 class="display-3" style="text-align: center">Low Carb</h2>
        <%= form_tag '/new_meal_card', method: :post, remote: true do %>
          <%= hidden_field_tag "carbs", "low-carbs" %>
          <%= submit_tag "+ New Meal", class: "btn btn-success new-meal-button" %>
        <% end %>
      </div>
      <%= render 'application_partials/daily_meal_card' %>
      <div class="lowcarb">

      </div>
    </div>
  </div>
</div>

app/views/dashboard/new_card.js.erb
var carbColum = {
  noCarb: ".nocarb",
  highCarb: ".highcarb",
  lowCarb: ".lowcarb"
}
carbs = ("<%= escape_javascript(@carbs) %>")
if (carbs === 'no-carbs') {
  $(".nocarb").append("<%= escape_javascript(render 'application_partials/daily_meal_card') %>");
} else if (carbs === 'high-carbs') {
  $(".highcarb").append("<%= escape_javascript(render 'application_partials/daily_meal_card') %>");
} else {
  $(".lowcarb").append("<%= escape_javascript(render 'application_partials/daily_meal_card') %>");
}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mealprep</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= yield %>
  <body>
  </body>
</html>

app/views/search/search.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Search for food item</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="search_form">
        <form action="<%= search_path %>" method="get">
          <%= text_field_tag(:search, params[:search], placeholder: "Search food item", autofocus: true, class: "form-control mr-sm-2" ) %>
          <%= button_tag(type: :submit, class: 'btn btn-outline-success my-2 my-sm-0') do %>
          Search
          <% end %>
        </form>
      </td>
      <th scope="col">Amount</th>
      <th scope="col">Protein</th>
      <th scope="col">Fat</th>
      <th scope="col">Carbs</th>
    </tr>
    <tr>
      <%= render "application_partials/search_results" %>
    </tr>
  </tbody>
</table>

app/views/search/search.js.erb
$("#searchForm").html("<%= escape_javascript(render 'application_partials/search_results') %>");

app/views/search/search_results.js.erb
$("#searchForm").html("<%= escape_javascript(render 'application_partials/search_results') %>");

app/views/search/summon_modal.js.erb
$("meowModal").html("<%= escape_javascript(render 'application_partials/create_item') %>");